lumail/lumail

src/index_view.cc
src/maildir_lua.cc
src/message_lua.cc
src/message_lua.h
src/message_view.cc
src/screen_lua.cc

Switch to using shared_ptr<CMessage> when passing to Lua, instead of bare pointers.  I think I've caught all cases, although there are some loose ends (eg push_cmessage() doesn't return an error if lua_newuserdata() doesn't fail).

Cmessage sharedptr

---

lumail2.lua

I found it confusing that Message:to_ctime() (and others, but I thought I'd start with an easy one) uses the ":" method syntax but ignores the self and passes the extra parameter.
So I've changed it to how I think it should work mainly to see if you agree or not.  :-)

Message:to_ctime() is using method syntax but ignoring the self.

---

lumail2.lua

* Change "static methods" to use "." notation
* Change the ones which take an object to use the method syntax, ie
Message:foo(msg) -> msg:foo().
* Some C++-implemented functions have not been updated.

Tidy up the use of Lua method syntax.

---

src/global_state.cc

There doesn't seem to be a reason to make these strings (historical reason?).

Fix maildir.max and index.max being initialised to strings

---

src/lua.cc
src/lua.h

* Call on_error in CLua::execute(), so that error checking/reporting is done
in a lot more cases.
* Factor out calling the Lua "on_error" function.

Improvement to Lua error reporting.

---

src/util.h

util.h uses std::vector without including it.
fixes #153

util.h: include vector to fix build

---

lumail2.lua

pcall gets a parameter which is not defined.
Use the "Date" header entry, stored in d, instead.
fixes #151

lumail.lua: fix Message:to_ctime()

---

lumail2.lua

I have another one for you.
At lumail2.lua:287 io.lines() is called with the argument "file" which is not defined.
io.input() sets the opened file as default file descriptor, so io.lines()
needs no argument at all.
**Additional changes:**
Store the path to the mailcap file in the local variable "mailcap_file".
Maybe this should be a global variable for easier modification by the user.
fixes #163

luamail2.lua: fix get_mime_viewer()

---

Makefile

These are commonly required to play well with various distributions' packaging systems.
This simplifies the process of packaging lumail as it allows the package build system to install lumail's files into a staging directory used for creating a software package without patching the Makefile.

Makefile: Heed PREFIX, SYSCONFDIR, and DESTDIR in install target

---

lib/cache.lua

This implements the first solution mentioned in #245.
Closes #245.

lib/cache.lua: convert cache entries to strings before calling gsub

---

lumail2.lua

lumail2.lua: change wrong variable name in generate_signature()

---

lumail2.lua

I noticed that the information printed to `Panel` differ between reply() and compose().

lumail2.lua: adapt the reply() info to the one of compose()

---

lumail2.lua
lumail2.user.lua

After my last pull request I realised that a lot other panel messages are
inconsistent, too.
My Approach to fix this mess:
Introduce three new wrappers for Panel:append. (on_error already existed but was
never used)
+ error_msg:    prints ERROR:, bold and red
+ warning_msg:  prints WARNING:, red
+ info_msg:     prints INFO:, yellow
Replace all uses of Panel:append(INFO | ERROR | WARNING) with one wrapper.
In the comments above the three wrappers I wrote a explanation about their use
cases.
Other changes:
+ adapt forward info to sent and reply
+ print "No message[s] found" as errors

lumail2.lua: unify messages written to the panel

---

lumail2.lua

This fixed both broken cases.
fixes #266.
* in message view we now select the message with the same index as the deleted, which is the next.
* [1,2,[3],4] => [1,2,[4]] => [1,2]
* In index view if the current index is bigger or equal to our message count we move it to the last message.
* [1,2,_3,4] => [1,2,_4] => [1,_2]
* #=4; i=2     => #=3; i=2 => #=2; i=1

lumail2.lua: fix UI Behaviour after deletion

---

lumail2.lua

This adds handling of wildcards in `get_mime_viewer()`.
E.g.: `image/*; imv %s;` will display all image formats with imv.
Why do we always return `less %s` for `text/html` ?
Can I remove it, because I would like to display html with lynx ?

lumail2.lua: handle wildcards in the mailcap file

---

lumail2.lua

This makes the jump command discoverable again.
The range of the registered jump commands is collected and
added to the bottom of the global keybindings.
E.g. `1-999 -> jump(N)`
Additional refactoring: 2 variables, `global` and `keys` were used to
hold the same value `keymap['global']`. Now there is only `global`.

include jump once in the keybindings view

---

lumail2.lua

When I want to answer with an encrypted mail I got the error from sh that the file `some@mail.tld` can't be found.
This PR strips the full name from `Someone <some@mail.tld>` and only
passes the email on.
I think this is only useful when answering but it doesn't hurt in the other
cases.

prevent "<" and ">" from appearing in a shell cmd

---

API.md
GPG.md
lib/gpg.lua
lumail2.lua

When I fixed the gpg error in reply I realised that our gpg support is scattered over many functions. So the first commit extracts duplicated gpg code into lib/gpg.lua.
The second commit adds a new config value `gpg.mode` which sets the gpg options without
user interaction. The behavior is documented in the code, the commit and GPG.md.
Some questions:
* Is it ok to use lumail specific functionality in a library ? (`Config:get`, `Screen:prompt`)
* Is it ok to present information to the user in a library ? (`info_msg`,`error_msg`)
I think this is mergeable. What do you think ?
**EDIT:** Now it is mergeable :)
Other possible gpg improvements would be:

Configurable defaults for gpg 

---

Makefile

Currently the `make install` target fails if no old configuration is found to be moved away.
This fixes it.

Do not fail if no old config exists

---

lib/gpg.lua

The regex to extract the recipients email address was wrong.
This and the fact that the recipients email wasn't quoted in the shell command
leaded to a bug and a serious security vulnerability.

fix gpg.defaults

---

API.md
HACKING.md
Makefile

Some files still mention `lumail2.lua` even the Makefile.

rename lumail2.lua to global.config.lua

---

global.config.lua
lib/threader.lua

This pull request adds thread aware functions, like `next_thread` or `thread_mark_read`.
`thread_next` mentioned in #317 is not implemented because we only have the thread information when `index.sort == "threads"` and then the next message in a thread is above the current one. So it would be useless.
The thread awareness is achieved by storing an array of root messages.
I didn't add default keybindings yet.
What do you think ?

Improve threading

---

API.md
global.config.lua
src/screen.cc
src/screen_lua.cc

I was annoyed because I couldn't complete file paths with spaces in them.
After reading the code I realized that I can't fix this because the c++ code makes assumption where to
complete.
So I came up with a more generic fix. Completions are now context aware.
To achieve this the function 'on_complete' now behaves like a filter for the line buffer used in `CSreen:get_line`. It calls the active context specific functions, which are called `complete_context`, collects their results, builds and returns the buffer.
This change comes with three contexts:
* address: using an external addressbook to complete email addresses
* path: complete file paths now even if they contain white space :)
* lua: no real changes here
What do you think ? It is really complicated but it's the best I came up with.

Improve completion

---

global.config.lua

I am totaly sorry for the trouble you have with the new completions and the code quality. :(
If you want to keep them here is a patch to fix completion if only one is available.
The solution used in c++ and mentioned in #330 is not correct.

fix completion if only one option is available

---

lib/threader.lua

Both now work within a thread.
We don't call trash or delete on the messages. Instead we call Message.trash once for every message in the thread.
Fixes #329.

Fix thread_trash and thread_delete

---

global.config.lua
lib/header_cache.lua
src/message.cc
src/message.h
src/message_lua.cc

This solves my problem of long gpg interactions and should speed up lumail in general.
Now messages once cached are only read from disk (parsed and decrypted) if their content is needed.
All information we need in index view is cached: amount of attachments and headers.
-> No need to read the file and invoke gpg.
The design of the header cache is really simple and it integrates well into existing code without much effort.
More information about the cache can be found at the top of `lib/header_cache.lua`.
Only Problem left with this is we don't recognise if headers change after they are cached. Is this important ? When and why do headers change on disk ?
But mtime of the message could be easily added to the cache.
This closes #340.

Header cache

---

src/screen.cc

If the user types printable characters they are added to a search string
and only completion candidates containing the search string are displayed.
The current search string gets printed in the bottom boarder of the window.
I wanted this for email completions maybe its usefull for others too.
It works for all kind of completions and doesn't change current behaviour.

add interactive string search to CScreen::choose_string

---

global.config.lua

Other email clients (only tested with thunderbird 52.8.0) have problems
with some utf8 runes (only tested with german umlauts) if the utf8 context
header is not added to the message prototype.
An encoding header is only missing if we don't use gmime to add another
mime part. If we add another mime part gmime maybe ignores our header or
is smart enough to use it. I can't see a difference in messages with
an attachment before and after this change.
**Thunderbird on the right**: A message send with lumail before the change.
**Lumail on the left**: A response send from thunderbird conatining new umlauts. There we see the
corrupted runes in the quoted text.
I think this happens because thunderbird fallbacks to some other encoding than we actually send.
@skx **I don't know if we acutally send …

send utf-8 encoding header

---

sample.lua/collapseable_threads.lua

Hi,
not sure whether such examples are desired in the repository. If not, that's okay.
This is an alternative implementation of the `index_view` function which is able to "collapse" threads based on "index.expand".
It is rudamentally tested, but there might be cases where this breaks things. Feel free to suggest improvements, of course!

Add sample of collapseable threads

---

Makefile

The distribution packagers will typically want to use their own compiler
warnings and optimization flags:
make CPPFLAGS="..."
However, this also overwrites the preprocessor defines, library/include
paths and the like. Let's mark the options the packager has no business
changing with the "override" keyword.

Makefile: allow changing CPPFLAGS

---

perl.d/Lumail.pm
perl.d/imap-proxy
src/global_state.cc
src/imap_proxy.cc
src/imap_proxy.h

Here's a fairly random collection of changes I chose to make when making Lumail work for me.
The only real fix there is the removal of the 1 second wait on spawning the IMAP helper, since that is too short for some of my machines (oh the lovely OLPC laptop); while perhaps being unnecessarily long for others. It probably deserves a better fix anyway though; but this seems to work well for now.

Some random fixes
